"""
BBC-AOS Knowledge Vault Manager — Phase 13D
Global knowledge vault (~/BBC_KNOWLEDGE/) manager.
Handles vault creation, Obsidian auto-detection, and project isolation.
"""

import os
import json
import shutil
import sys
from pathlib import Path
from typing import Optional, Dict, Any


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VAULT_ROOT_NAME = "BBC_KNOWLEDGE"
VAULT_SUBFOLDERS = [
    "Decisions",
    "Executions",
    "Replays",
    "Failures",
    "Architecture",
    "Lessons_Learned",
]


def get_global_vault_root() -> Path:
    """Return the path to the global BBC_KNOWLEDGE vault (cross-platform)."""
    return Path.home() / VAULT_ROOT_NAME


def get_project_vault_path(project_id: str) -> Path:
    """Return the path to a specific project's vault inside the global vault."""
    return get_global_vault_root() / "Projects" / project_id


# ---------------------------------------------------------------------------
# Obsidian Auto-Detection
# ---------------------------------------------------------------------------

_OBSIDIAN_WINDOWS_PATHS = [
    Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Obsidian" / "Obsidian.exe",
    Path("C:/Program Files/Obsidian/Obsidian.exe"),
    Path("C:/Program Files (x86)/Obsidian/Obsidian.exe"),
]

_OBSIDIAN_MACOS_PATHS = [
    Path("/Applications/Obsidian.app"),
]

_OBSIDIAN_LINUX_PATHS = [
    Path("/usr/bin/obsidian"),
    Path("/usr/local/bin/obsidian"),
    Path(os.environ.get("HOME", "")) / ".local/bin/obsidian",
]


def detect_obsidian() -> Optional[str]:
    """
    Auto-detect Obsidian installation.

    Returns:
        Absolute path string to the Obsidian executable/app, or None if not found.
    """
    if sys.platform == "win32":
        # Check registry (optional, skip silently if winreg unavailable)
        try:
            import winreg
            key = winreg.OpenKey(
                winreg.HKEY_LOCAL_MACHINE,
                r"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Obsidian.exe",
            )
            path_val, _ = winreg.QueryValueEx(key, "")
            winreg.CloseKey(key)
            if path_val and os.path.exists(path_val):
                return str(path_val)
        except Exception:
            pass
        # Fallback: common install paths
        for candidate in _OBSIDIAN_WINDOWS_PATHS:
            if candidate.exists():
                return str(candidate)

    elif sys.platform == "darwin":
        for candidate in _OBSIDIAN_MACOS_PATHS:
            if candidate.exists():
                return str(candidate)

    else:
        # Linux: PATH lookup first
        import shutil as sh
        found = sh.which("obsidian")
        if found:
            return found
        for candidate in _OBSIDIAN_LINUX_PATHS:
            if candidate.exists():
                return str(candidate)

    return None


# ---------------------------------------------------------------------------
# Vault Lifecycle
# ---------------------------------------------------------------------------

def vault_init(project_id: Optional[str] = None) -> Path:
    """
    Create the global BBC_KNOWLEDGE vault and (optionally) a project sub-vault.

    Args:
        project_id: Optional project identifier. Creates a project folder if given.

    Returns:
        Path to the created vault root.
    """
    vault_root = get_global_vault_root()
    vault_root.mkdir(parents=True, exist_ok=True)
    (vault_root / "Projects").mkdir(exist_ok=True)

    # Create global .obsidian stub so Obsidian can open the root as a vault
    obsidian_cfg = vault_root / ".obsidian"
    obsidian_cfg.mkdir(exist_ok=True)
    app_json = obsidian_cfg / "app.json"
    if not app_json.exists():
        app_json.write_text("{}", encoding="utf-8")

    # Write vault README
    readme = vault_root / "README.md"
    if not readme.exists():
        readme.write_text(
            "# BBC Knowledge Vault\n\n"
            "Auto-generated by BBC-AOS. Open this folder as a vault in Obsidian.\n\n"
            "All project knowledge is organized under `Projects/<project_id>/`.\n",
            encoding="utf-8",
        )

    # Create project subfolder if requested
    if project_id:
        project_path = vault_root / "Projects" / project_id
        project_path.mkdir(parents=True, exist_ok=True)
        for folder in VAULT_SUBFOLDERS:
            (project_path / folder).mkdir(exist_ok=True)

    return vault_root


def vault_status() -> Dict[str, Any]:
    """
    Return status information about the global vault.

    Returns:
        Dict with keys: exists, path, project_count, obsidian_path
    """
    vault_root = get_global_vault_root()
    projects_dir = vault_root / "Projects"
    project_count = 0
    if projects_dir.exists():
        project_count = len([d for d in projects_dir.iterdir() if d.is_dir()])

    return {
        "exists": vault_root.exists(),
        "path": str(vault_root),
        "project_count": project_count,
        "obsidian_path": detect_obsidian(),
    }


def vault_open() -> bool:
    """
    Open the global BBC_KNOWLEDGE vault in the system file explorer.

    Returns:
        True if opened successfully, False otherwise.
    """
    vault_root = get_global_vault_root()
    if not vault_root.exists():
        return False
    try:
        if sys.platform == "win32":
            os.startfile(str(vault_root))  # type: ignore[attr-defined]
        elif sys.platform == "darwin":
            import subprocess
            subprocess.call(["open", str(vault_root)])
        else:
            import subprocess
            subprocess.call(["xdg-open", str(vault_root)])
        return True
    except Exception:
        return False


def vault_disconnect(bbc_dir: str = ".bbc") -> None:
    """
    Remove vault integration settings from .bbc/config.json.

    Args:
        bbc_dir: Path to the .bbc directory (default: current project).
    """
    config_path = os.path.join(bbc_dir, "config.json")
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
        config.pop("vault", None)
        config.pop("obsidian", None)
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)


def vault_migrate_wiki(source_wiki_dir: str) -> Optional[str]:
    """
    Migrate an existing BBC_Wiki/ directory into the global vault.

    Args:
        source_wiki_dir: Path to the existing BBC_Wiki directory.

    Returns:
        Destination path string if migrated, None if source not found.
    """
    src = Path(source_wiki_dir)
    if not src.exists():
        return None

    # Derive project_id from parent directory name
    project_id = src.parent.name
    dest = get_project_vault_path(project_id)
    dest.mkdir(parents=True, exist_ok=True)

    for item in src.iterdir():
        dest_item = dest / item.name
        if item.is_dir():
            if dest_item.exists():
                shutil.copytree(str(item), str(dest_item), dirs_exist_ok=True)
            else:
                shutil.copytree(str(item), str(dest_item))
        else:
            shutil.copy2(str(item), str(dest_item))

    return str(dest)
